steps:

- task: MicroBuildSigningPlugin@1
  inputs:
    signType: $(SignType)
    zipSources: false
  displayName: Install MicroBuild Signing Plugin
  condition: and(succeeded(), ne(variables['Hosted'], 'true'))
