steps:

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: tests/MessagePack.Tests/MessagePack.Tests.csproj
    arguments: /p:platform=NoVSIX -c $(BuildConfiguration) -f netcoreapp2.1 -v n
    testRunTitle: netcoreapp2.1-$(Agent.JobName)
